### ISSUE TITLE
Usage with jest

### ISSUE THREAD

**Issue by pokidovea** [bmatcuk/mock-css-modules#1]
Hello, can you show me, how to use it with jest?

**Comment by bmatcuk** [comment]
Unfortunately, I've never used jest, so I'm not sure. But, looking through the documentation, I *think* it could be done by creating a file called, for example, `setup.js` and putting the following in:

```javascript
require("mock-css-modules");
```

Then, in your `package.json`, add the following:

```javascript
{
  ...
  "jest": {
    "setupFiles": ['./setup.js']
  }
  ...
}
```

Let me know if that works and I'll add it to the documentation for mock-css-modules =)

**Comment by pokidovea** [comment]
I found a tutorial about testing CSS-modules with jest. [https://facebook.github.io/jest/docs/tutorial-webpack.html#content](url). Solution is absolutely the same as yours, but there used another lib.
You can adapt this solution for your lib, if you want.
Thanks.

**Comment by bmatcuk** [comment]
Thanks for the heads up =)
